name: fono-api

services:
  database:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fono
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fono"]
      interval: 5s
      timeout: 5s
      retries: 10

  audio-transcription-api:
    image: mateusumelo/c317-whisper-api-audio-transcription-api
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=false
      - WHISPER_MODEL_SIZE=base
      - WHISPER_DEVICE=cpu
      - WHISPER_COMPUTE_TYPE=int8
      - MAX_AUDIO_SIZE_MB=25
      - MODEL_CACHE_DIR=/app/models
      - TEMP_UPLOAD_DIR=/tmp
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/fono?schema=public
    volumes:
      - ./data/temp_uploads:/tmp
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    depends_on:
      database:
        condition: service_healthy
      audio-transcription-api:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/fono?schema=public
      - SECRET_KEY=super_secret_key_troque_isso_aqui
      - TRANSCRIPTION_API_URL=http://audio-transcription-api:3000/api/v1/transcribe/file
      - TEST_AUDIO_PATH=assets/audios
      - DEFAULT_AUDIO_FILE=teste.ogg
      - EXPECTED_TRANSCRIPTION=Teste de transcrição
    ports:
      - 3001:3000
